const COMMANDS = Object.freeze({
  CURRENT_PORTFOLIO: 'CURRENT_PORTFOLIO',
  CALCULATE_OVERLAP: 'CALCULATE_OVERLAP',
  OVERLAP_PERCENTAGE: 'OVERLAP_PERCENTAGE',
  ADD_STOCK: 'ADD_STOCK',
});

module.exports = COMMANDS;
